sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-9.0.0.0
before_script:
  - gem install bundler # To use bundler 1.10
  - "bundle exec appraisal install"
script: "bundle exec rake appraisal test"
